myopenglapp: code_3_9.o objtovert2.o
		 gcc -o myopenglapp code_3_9.o objtovert2.o -lglut -lGL -lGLU

code_3_9.o: code_3_9.c openglsb.h
	    gcc -c code_3_9.c

objtovert2.o: objtovert2.c
		gcc -c objtovert2.c
